### ISSUE TITLE
Question: tunnelling suggestion for E2E tests

### ISSUE THREAD

**Issue by brbrr** [anderspitman/awesome-tunneling#11]
Hey! Thank you so much for collecting this awesome list! 

I am currently using localtunnel, and it fits my usecase pretty well, although I have doubts about its stability. Can you suggest a service with the following requirements:
- (if paid) no limits on running tunnels
- randomly generated subdomains
- SSL
- relatively easy way to get generated URL outside of the terminal window with running client

I went through (most) of the services in this list, and unfortunately, I was not been able to find something that will fit my needs. 

Thanks!

**Comment by anderspitman** [comment]
Actually you're probably more familiar with the various options at this point than I am. It pretty quickly became apparent none of them quite worked the way I wanted, which is why I created SirTunnel and boringproxy for my own use.

That said, does ngrok not cover your needs? I haven't used it heavily so don't know where it falls short.

PS - If you can suggest additional useful information for any of the tools you tried to help future readers it would be greatly appreciated.

**Comment by anderspitman** [comment]
Also, if you're comfortable running your own VPS, you could easily SirTunnel to meet all your needs. Check out the source code; there's not much going on in there.
