### ISSUE TITLE
Android Tunneling Client support? 

### ISSUE THREAD

**Issue by t2t-sonbui** [anderspitman/awesome-tunneling#158]
The services are excellent and suitable for many different uses. But I'm not sure if any of the services listed here support Android tunneling  clients. I have some apps running on android that need to use it, at least TCP. I want to add that service to my application so that clients can use it more easily instead of sharing the connection over the local network, then using the client from the computer

**Comment by anderspitman** [comment]
Tailscale is the best thing I can think of. Maybe combined with their Funnel service?

I'm not aware of any pure tunnels that run on Android. I prototyped this a few years ago with boringproxy. It worked, but it was a pain to implement and I never really got it to a usable status.

I think the problem is there's not currently much server software that runs on Android.
